// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountTo: typeof import('./../src/components/count-to/src/count-to.vue')['default']
    ImportExcel: typeof import('./../src/components/excel/src/import-excel.vue')['default']
    JsonEditor: typeof import('./../src/components/json-editor/src/json-editor.vue')['default']
    List: typeof import('./../src/components/list/src/list.vue')['default']
    ListItem: typeof import('./../src/components/list/src/list-item.vue')['default']
    ListItemMeta: typeof import('./../src/components/list/src/list-item-meta.vue')['default']
    Markdown: typeof import('./../src/components/markdown/src/markdown.vue')['default']
    Panel: typeof import('./../src/components/mousemove-panel/src/panel.vue')['default']
    TableSettings: typeof import('./../src/components/table-settings/src/table-settings.vue')['default']
  }
}

export { }
