// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountTo: typeof import('./../src/components/count-to/src/count-to.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ImportExcel: typeof import('./../src/components/excel/src/import-excel.vue')['default']
    JsonEditor: typeof import('./../src/components/json-editor/src/json-editor.vue')['default']
    List: typeof import('./../src/components/list/src/list.vue')['default']
    ListItem: typeof import('./../src/components/list/src/list-item.vue')['default']
    ListItemMeta: typeof import('./../src/components/list/src/list-item-meta.vue')['default']
    Markdown: typeof import('./../src/components/markdown/src/markdown.vue')['default']
    Panel: typeof import('./../src/components/mousemove-panel/src/panel.vue')['default']
    RichEditor: typeof import('./../src/components/rich-editor/src/rich-editor.vue')['default']
    TableSettings: typeof import('./../src/components/table-settings/src/table-settings.vue')['default']
  }
}

export { }
